# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/MyDesign/MyDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign || ORIG_REF_NAME==MyDesign} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_counter_4bits_0_0/MyDesign_counter_4bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_counter_4bits_0_0 || ORIG_REF_NAME==MyDesign_counter_4bits_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_bundle_splitter_mux_0_0/MyDesign_bundle_splitter_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_bundle_splitter_mux_0_0 || ORIG_REF_NAME==MyDesign_bundle_splitter_mux_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_bundle_splitter_dec_0_0/MyDesign_bundle_splitter_dec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_bundle_splitter_dec_0_0 || ORIG_REF_NAME==MyDesign_bundle_splitter_dec_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_decoder_2x4_0_0/MyDesign_decoder_2x4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_decoder_2x4_0_0 || ORIG_REF_NAME==MyDesign_decoder_2x4_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_multiplexer_4x1_0_0/MyDesign_multiplexer_4x1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_multiplexer_4x1_0_0 || ORIG_REF_NAME==MyDesign_multiplexer_4x1_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_inverter_0_0/MyDesign_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_inverter_0_0 || ORIG_REF_NAME==MyDesign_inverter_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_lookUp_table_0_0/MyDesign_lookUp_table_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_lookUp_table_0_0 || ORIG_REF_NAME==MyDesign_lookUp_table_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_display_0_0/MyDesign_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_display_0_0 || ORIG_REF_NAME==MyDesign_display_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_clock_scaler1_0_0/MyDesign_clock_scaler1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_clock_scaler1_0_0 || ORIG_REF_NAME==MyDesign_clock_scaler1_0_0} -quiet] -quiet

# IP: bd/MyDesign/ip/MyDesign_latch_0_0/MyDesign_latch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MyDesign_latch_0_0 || ORIG_REF_NAME==MyDesign_latch_0_0} -quiet] -quiet

# XDC: bd/MyDesign/MyDesign_ooc.xdc
