# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinLayout1.xdc

# Block Designs: bd/TopLevel/TopLevel.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel || ORIG_REF_NAME==TopLevel} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_counter_4bits_0_0/TopLevel_counter_4bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_counter_4bits_0_0 || ORIG_REF_NAME==TopLevel_counter_4bits_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_decoder_2x4_0_0/TopLevel_decoder_2x4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_decoder_2x4_0_0 || ORIG_REF_NAME==TopLevel_decoder_2x4_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_bundle_splitter_mux_0_0/TopLevel_bundle_splitter_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_bundle_splitter_mux_0_0 || ORIG_REF_NAME==TopLevel_bundle_splitter_mux_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_bundle_splitter_dec_0_0/TopLevel_bundle_splitter_dec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_bundle_splitter_dec_0_0 || ORIG_REF_NAME==TopLevel_bundle_splitter_dec_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_lookUp_table_0_0/TopLevel_lookUp_table_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_lookUp_table_0_0 || ORIG_REF_NAME==TopLevel_lookUp_table_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_multiplexer_4x1_0_0/TopLevel_multiplexer_4x1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_multiplexer_4x1_0_0 || ORIG_REF_NAME==TopLevel_multiplexer_4x1_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_inverter_0_0/TopLevel_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_inverter_0_0 || ORIG_REF_NAME==TopLevel_inverter_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_clock_scaler1_0_0/TopLevel_clock_scaler1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_clock_scaler1_0_0 || ORIG_REF_NAME==TopLevel_clock_scaler1_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_latch_0_0/TopLevel_latch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_latch_0_0 || ORIG_REF_NAME==TopLevel_latch_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_debounce_0_0/TopLevel_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_debounce_0_0 || ORIG_REF_NAME==TopLevel_debounce_0_0} -quiet] -quiet

# IP: bd/TopLevel/ip/TopLevel_display_0_0/TopLevel_display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevel_display_0_0 || ORIG_REF_NAME==TopLevel_display_0_0} -quiet] -quiet

# XDC: bd/TopLevel/TopLevel_ooc.xdc
