webtalk_init -webtalk_dir /home/runge/Subjects/Embedded/code/mC/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-06 11:52:55" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fakcplukf73164il3nqmmndo31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1308.957 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.689 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1601976045000" -context "sdk\\\\bsp/1601976045000"
webtalk_add_data -client sdk -key hwid -value "1601974280000" -context "sdk\\\\bsp/1601976045000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1601976045000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1601976045000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1601976045000"
webtalk_add_data -client sdk -key uid -value "1601976102000" -context "sdk\\\\bsp/1601976102000"
webtalk_add_data -client sdk -key hwid -value "1601974280000" -context "sdk\\\\bsp/1601976102000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1601976102000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1601976102000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1601976102000"
webtalk_add_data -client sdk -key uid -value "1601976103000" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key hwid -value "1601974280000" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key bspid -value "1601976102000" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key projSize -value "186.62890625" -context "sdk\\\\application/1601976103000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key DebugCount -value "4" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1601977974995"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1601977974995"
webtalk_transmit -clientid 4151427320 -regid "" -xml /home/runge/Subjects/Embedded/code/mC/webtalk/usage_statistics_ext_sdk.xml -html /home/runge/Subjects/Embedded/code/mC/webtalk/usage_statistics_ext_sdk.html -wdm /home/runge/Subjects/Embedded/code/mC/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
